language: java
sudo: false
install: true

jdk:
  - oraclejdk8

env:
  - SONARQUBE_VERSION=5.6.7
  - SONARQUBE_VERSION=6.5
  - SONARQUBE_VERSION=6.6

install:
  - mvn dependency:go-offline --update-snapshots --show-version

script:
  - mvn compile test package --errors
  - mvn verify -Dsonar.runtimeVersion=$SONARQUBE_VERSION --errors

after_script:
  - mvn org.codehaus.mojo:license-maven-plugin:aggregate-add-third-party -Dlicense.includedScopes=compile

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

notifications:
  email: false
  on_start: always

addons:
  apt:
    packages:
      # upgrade java 8 as the default version 1.8.0_31 prevents from compiling sources
      # https://github.com/travis-ci/travis-ci/issues/4042
      - oracle-java8-installer
